### ISSUE TITLE
Unable to build ios after installing the plugin

### ISSUE THREAD

**Issue by mhammad-extron** [AraHovakimyan/cordova-plugin-wkwebviewxhrfix#10]
I upgraded Cordova to 11.0.0 and Cordova iOS to 6.3.0, and now it is unable to build it. Error is related to this plugin.

The following build commands failed:
        CompileC /Users/..../CDVWKWebViewEngine+FileXhrFix.o /Users/.../Plugins/cordova-plugin-wkwebviewxhrfix/CDVWKWebViewEngine+FileXhrFix.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'MyProject' from project 'MyProject')
(1 failure)

Looks like allowFileAccessFromFileURLs is deprecated

**Comment by AraHovakimyan** [comment]
I just checked for my project with  Cordova 11.0.0 and Cordova-iOS 6.3.0. All are working Fine.
I see you have problems with the file CDVWKWebViewEngine,  The plugin doesn't have such a file, it's probably from another plugin. 
I recommend uninstalling and then reinstalling the plugin.

1. First remove the cordova-plugin-wkwebviewxhrfix plugin by
`Cordova plugin rm cordova-plugin-wkwebviewxhrfix`

2. Install plugin AraHovakimyan/cordova-plugin-wkwebviewxhrfix by
`cordova plugin add https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix`

Message Please about the results

**Comment by mhammad-extron** [comment]
Done.
Still same error.

To build, I am using 
`cordova build ios --target="iPad-Air-5th-generation, 16.2"`

Target device uses iOS 16.2

Error is in file CDVWKWebViewEngine+FileXhrFix.h

```
/Users/.../ios/MyProject/Plugins/cordova-plugin-wkwebviewxhrfix/CDVWKWebViewEngine+FileXhrFix.h:9:9: fatal error: 
      'CDVWKWebViewEngine.h' file not found
#import "CDVWKWebViewEngine.h"
        ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.

```

**Comment by mhammad-extron** [comment]
Found the problem.

After removing and adding it back again as suggested, it installs multiple version of this plugin
![image](https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix/assets/74072383/6eaae4d7-f8c8-4035-aa59-69bfcc8ebe6a)

The last one uses
#import "CDVWKWebViewEngine.h"

**Comment by AraHovakimyan** [comment]
Please remove again and try to install from npm using

cordova plugin add @ahovakimyan/cordova-plugin-wkwebviewxhrfix

**Comment by AraHovakimyan** [comment]
The second is a different plugin and you can safely delete it. I will try to understand why the second version is installed.

**Comment by AraHovakimyan** [comment]
also you can fork the plugin and try to install from your GitHub

**Comment by AraHovakimyan** [comment]
Please let me know if it will be fixed for you

**Comment by mhammad-extron** [comment]
I uninstalled, deleted both folders, made sure it does not exist in fetch.json/ios.json/config.xml, forked and installed from my Github. Still same results. I see two versions of the plugin installed.

**Comment by mhammad-extron** [comment]
I also noticed that access to local files are not supported from iOS 16.4 if app or http is used as schema

**Comment by mhammad-extron** [comment]
I found the issue. I added this plugin as dependency in angular.json by mistake. Removed and installed again. Found no multiple versions. Thanks for your help.
