### ISSUE TITLE
Cannot load local resources due to file:// protocol.

### ISSUE THREAD

**Issue by csantanu** [AraHovakimyan/cordova-plugin-wkwebviewxhrfix#2]
We are using cordova iOS 6.1.1, oracle's plugin and this plugin, without any scheme in config.xml. The build is successful and the app works fine in the device except when loading local files which gets downloaded from remote server backend. Our's is an ebook app, where we download and display user's ebooks (epub format) in the library. The book cover images and epub files gets downloaded correctly as evident from the console output. We are using cordova file transfer plugin, the files when gets stored in the device Library folder, shows file:/// in the beginning of the file names. Then the web inspector shows the operation not permitted / cannot load resources error. We tried various things, but cannot go pass this hurdle. Any help will be highly appreciated.

**Comment by AraHovakimyan** [comment]
Hi. Just a question: Do you using "apache/cordova-plugin-whitelist"?
https://github.com/apache/cordova-plugin-whitelist

**Comment by SandroMoretti** [comment]
> 
> 
> Hi. Just a question: Do you using "apache/cordova-plugin-whitelist"?
> https://github.com/apache/cordova-plugin-whitelist

For load local files under file://, is needed to use whitelist or can't have whitelist?
I'm using whitelist in my project, and can't load file:// requests.

**Comment by SandroMoretti** [comment]
I'm using cordova ios 6.0.0 and this plugin resolve this problem for me.

I'm using whitelist plugin. I removed cordova-plugin-file-xhr and webview-engine. All that I made is this plugin and everything just work.

**Comment by csantanu** [comment]
Yes, we are using - cordova-plugin-whitelist 1.3.4 "Whitelist"
Update: we have resolved the issue with loading images downloaded from remote location by sanitizing the URL, since we are using angular (ionic). But the ePUB file still not rendering within the iframe.

**Comment by tatva210** [comment]
A similar problem, local images downloaded from a remote location are not showing. I am also using cordova-plugin-whitelist.

**Comment by elielnfinic** [comment]
Hello everybody,

I had that issue and spent many days trying to find a solution and the links are working if they are converted with the function window.WkWebView.convertFilePath(url)

`
E.g 
var url = "file://path/to/a/location";
var new_url = window.WkWebView.convertFilePath(url);
`

Before you `cordova prepare`, add the following to the config.xml
`
<platform name="ios">    
  <preference name="scheme" value="app" />
  <preference name="hostname" value="localhost" />
 </platform>
`

Solution inspired by [this ansswer on stackoverflow](https://stackoverflow.com/questions/63814652/cordova-cordova-ios-6-1-0-load-local-image).

Thanks.

**Comment by csantanu** [comment]
@elielnfinic Yes, I solved the issue with the similar approach as you mentioned. Thanks. Closing the issue.

**Comment by attex** [comment]
Hi there,

i tried everything from your comments and nothing works for me.

com-sarriaroman-photoviewer 1.2.4 "PhotoViewer"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.4-dev "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file-opener2 2.2.1 "File Opener2"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 11.0.3 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-media-capture 3.0.3 "Capture"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-reports 0.1.0 "Dynamic Reports"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-streaming-media 2.2.0 "StreamingMedia"
cordova-plugin-vue-pinboard-component 0.1.0 "Pinboard"
cordova-plugin-wkwebviewxhrfix 1.0.0 "Cordova WKWebView File XHR Fix"
cordova-sqlite-storage 5.1.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
nl.x-services.plugins.videocaptureplus 1.0.0 "VideoCapturePlus"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"

Thats my pluginlist. 
I am trying to load a image in the background-image style tag with:
background-imgae:url('file:///var/mobile/Containers/Data/Application/...../Library/NoCloud/APP/Adresse/1000006000/1613467053393.jpg')

I already tried window.WkWebView.convertFilePath(url); but the resulting path does not differ from the original. 
I am just getting the error: "Failed to load resource"

Can anyone help me ?

**Comment by AraHovakimyan** [comment]
Please try to use @elielnfinic  solution without using this plugin.

**Comment by attex** [comment]
@AraHovakimyan when using <preference name="scheme" value="app" /> my app cannot connect to my server due to: Origin app://localhost is not allowed by Access-Control-Allow-Origin.

**Comment by AraHovakimyan** [comment]
Try adding also another plugin cordova-plugin-wkwebview-file-xhr.
I think this will help to solve that issue

`https://github.com/oracle/cordova-plugin-wkwebview-file-xhr`

If you get the result, please let me know.

**Comment by AraHovakimyan** [comment]
If you use the plugin 

`cordova plugin add @ahovakimyan/cordova-plugin-wkwebviewxhrfix`

you need to remove the following lines from config.xml

```
<platform name="ios">    
  <preference name="scheme" value="app" />
  <preference name="hostname" value="localhost" />
</platform>
```
