### ISSUE TITLE
Breaks the build

### ISSUE THREAD

**Issue by jfoclpf** [AraHovakimyan/cordova-plugin-wkwebviewxhrfix#5]
After I installed this plugin, the build is breaking  upon `cordova build ios`

```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/user926670/Library/Developer/Xcode/DerivedData/No_meu_Bairro!-fvrayykohoddbcghkiuhdagxegbh/Build/Intermediates.noindex/No\ meu\ Bairro!.build/Debug-iphonesimulator/No\ meu\ Bairro!.build/Objects-normal/x86_64/CDVWKWebViewEngine+FileXhrFix.o /Users/user926670/dev/in-my-district/platforms/ios/No\ meu\ Bairro!/Plugins/cordova-plugin-wkwebviewxhrfix/CDVWKWebViewEngine+FileXhrFix.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
```

Output of cordova info

```
Cordova Packages:

    cli: 10.0.0
        common: 4.0.2
        create: 3.0.0
        lib: 10.0.0
            common: 4.0.2
            fetch: 3.0.0
            serve: 4.0.0

Project Installed Platforms:

    ios: 6.2.0

Project Installed Plugins:

    cordova-pdf-generator: 2.1.1
    cordova-plugin-androidx-adapter: 1.1.3
    cordova-plugin-app-version: 0.1.12
    cordova-plugin-camera: 5.0.3
    cordova-plugin-device: 2.0.3
    cordova-plugin-email-composer: 0.9.2
    cordova-plugin-file: 6.0.2
    cordova-plugin-geolocation: 4.1.0
    cordova-plugin-inappbrowser: 5.0.0
    cordova-plugin-is-debug: 1.0.0
    cordova-plugin-network-information: 3.0.0
    cordova-plugin-screen-orientation: 3.0.2
    cordova-plugin-simple-image-resizer: 0.1.1
    cordova-plugin-splashscreen: 6.0.0
    cordova-plugin-statusbar: 2.4.3
    cordova-plugin-whitelist: 1.3.5
    cordova-plugin-wkwebviewxhrfix: 0.1.0

Environment:

    OS: macOS Catalina 10.15.7 (19H1323) (darwin 19.6.0) x64
    Node: v12.16.2
    npm: 6.14.4

ios Environment:

    xcodebuild:
Xcode 12.4
Build version 12D4e


Project Setting Files:

    config.xml:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<widget id="com.in.my.district" version="1.2.10" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <name>No meu Bairro!</name>
  <description>
    Comunique ao seu município anomalias no seu bairro, como buracos na calçada ou lixo por recolher
  </description>
  <author email="joao.pimentel.ferreira@gmail.com" href="https://www.joaopimentel.com/">
    João Pimentel Ferreira
  </author>
  <content src="index.html"/>
  <icon height="512" src="res/icon/universal/icon4_512x512_playstore.png" width="512"/>
  <icon density="xhdpi" height="196" src="res/icon/universal/icon4_XHDPI_196x196_320dpi.png" width="196"/>
  <icon density="xxxhdpi" height="192" src="res/icon/universal/icon4_XXXHDPI_192x192_640dpi.png" width="192"/>
  <icon density="xxhdpi" height="144" src="res/icon/universal/icon4_XXHDPI_144x144_480dpi.png" width="144"/>
  <icon density="hdpi" height="72" src="res/icon/universal/icon4_HDPI_72x72_240dpi.png" width="72"/>
  <icon density="mdpi" height="48" src="res/icon/universal/icon4_MDPI_48x48_160dpi.png" width="48"/>
  <access origin="*"/>
  <allow-navigation href="*"/>
  <allow-intent href="http://*/*"/>
  <allow-intent href="https://*/*"/>
  <preference name="OverrideUserAgent" value="APP/com.in.my.district"/>
  <preference name="windows-target-version" value="10.0"/>
  <preference name="windows-phone-target-version" value="10.0"/>
  <preference name="iosExtraFilesystems" value="library,library-nosync,documents,documents-nosync,cache,bundle"/>
  <preference name="AndroidExtraFilesystems" value="files,files-external,documents,sdcard,cache,cache-external,assets"/>
  <preference name="StatusBarOverlaysWebView" value="false"/>
  <preference name="StatusBarBackgroundColor" value="#FFFFFF"/>
  <preference name="StatusBarStyle" value="blacktranslucent"/>
  <preference name="AndroidXEnabled" value="true"/>
  <hook src="hooks/copyCredentials.js" type="before_prepare"/>
  <hook src="hooks/convertHbsToHtml.js" type="after_prepare"/>
  <hook src="hooks/minifyFiles.js" type="after_prepare"/>
  <hook src="node_modules/cordova-import-npm/scripts/importNpmPackages.js" type="before_prepare"/>
  <platform name="android">
    <preference name="android-minSdkVersion" value="22"/>
    <preference name="android-targetSdkVersion" value="29"/>
    <preference name="AndroidPersistentFileLocation" value="Compatibility"/>
    <allow-intent href="market:*"/>
    <icon height="512" src="res/icon/android/512.png" width="512"/>
    <icon density="xhdpi" height="192" src="res/icon/android/192.png" width="192"/>
    <icon density="xxxhdpi" height="192" src="res/icon/android/192.png" width="192"/>
    <icon density="xxhdpi" height="144" src="res/icon/android/144.png" width="144"/>
    <icon density="hdpi" height="72" src="res/icon/android/72.png" width="72"/>
    <icon density="mdpi" height="48" src="res/icon/android/48.png" width="48"/>
    <splash density="hdpi" src="res/screen/android/screen-hdpi-portrait.png"/>
    <splash density="port-hdpi" src="res/screen/android/screen-hdpi-portrait.png"/>
    <splash density="ldpi" src="res/screen/android/screen-ldpi-portrait.png"/>
    <splash density="port-ldpi" src="res/screen/android/screen-ldpi-portrait.png"/>
    <splash density="mdpi" src="res/screen/android/screen-mdpi-portrait.png"/>
    <splash density="port-mdpi" src="res/screen/android/screen-mdpi-portrait.png"/>
    <splash density="xhdpi" src="res/screen/android/screen-xhdpi-portrait.png"/>
    <splash density="port-xhdpi" src="res/screen/android/screen-xhdpi-portrait.png"/>
  </platform>
  <platform name="ios">
    <allow-intent href="itms:*"/>
    <allow-intent href="itms-apps:*"/>
    <icon src="res/icon/ios/48.png" width="48" height="48"/>
    <icon src="res/icon/ios/92.png" width="92" height="92"/>
    <icon src="res/icon/ios/72.png" width="72" height="72"/>
    <icon src="res/icon/ios/144.png" width="144" height="144"/>
    <icon src="res/icon/ios/192.png" width="192" height="192"/>
    <icon src="res/icon/ios/512.png" width="512" height="512"/>
    <preference name="iosPersistentFileLocation" value="Library"/>
    <edit-config target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
      <string>Necessita da sua localização para indicar o endereço da ocorrência a ser enviada ao seu município</string>
    </edit-config>
    <edit-config target="NSLocationAlwaysAndWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
      <string>Necessita da sua localização para indicar o endereço da ocorrência a ser enviada ao seu município</string>
    </edit-config>
    <edit-config target="NSLocationAlwaysUsageDescription" file="*-Info.plist" mode="merge">
      <string>Necessita da sua localização para indicar o endereço da ocorrência a ser enviada ao seu município</string>
    </edit-config>
    <edit-config target="NSLocationAlwaysAndWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
      <string>Necessita da sua localização para indicar o endereço da ocorrência a ser enviada ao seu município</string>
    </edit-config>
    <edit-config target="NSCameraUsageDescription" file="*-Info.plist" mode="merge">
      <string>Necessita da acesso à câmera para tirar fotos às anomalias</string>
    </edit-config>
    <edit-config target="NSPhotoLibraryUsageDescription" file="*-Info.plist" mode="merge">
      <string>Necessita da acesso à galeria, caso você já tenha tirado anteriormente a foto à ocorrência</string>
    </edit-config>
    <edit-config target="NSPhotoLibraryAddUsageDescription" file="*-Info.plist" mode="merge">
      <string>Necessita da acesso à galeria para guardar algumas fotos, mesmo que temporariamente</string>
    </edit-config>
    <edit-config target="UIFileSharingEnabled" file="*-Info.plist" mode="merge">
      <true/>
    </edit-config>
    <edit-config target="LSSupportsOpeningDocumentsInPlace" file="*-Info.plist" mode="merge">
      <true/>
    </edit-config>
    <edit-config target="UISupportsDocumentBrowser" file="*-Info.plist" mode="merge">
      <true/>
    </edit-config>
  </platform>
</widget>

    package.json:
--- Start of Cordova JSON Snippet ---
{
  "plugins": {
    "cordova-plugin-geolocation": {
      "GPS_REQUIRED": "true"
    },
    "cordova-plugin-email-composer": {
      "ANDROID_SUPPORT_V4_VERSION": "27.+"
    },
    "cordova-plugin-statusbar": {},
    "cordova-plugin-screen-orientation": {},
    "cordova-plugin-device": {},
    "cordova-plugin-whitelist": {},
    "cordova-pdf-generator": {},
    "cordova-plugin-splashscreen": {},
    "cordova-plugin-inappbrowser": {},
    "cordova-plugin-is-debug": {},
    "cordova-plugin-simple-image-resizer": {
      "ANDROID_EXIFINTERFACES_VERSION": "27.+"
    },
    "cordova-plugin-androidx-adapter": {},
    "cordova-plugin-file": {},
    "cordova-plugin-camera": {
      "ANDROID_SUPPORT_V4_VERSION": "27.+"
    },
    "cordova-plugin-network-information": {},
    "cordova-plugin-app-version": {},
    "cordova-plugin-wkwebviewxhrfix": {}
  },
  "platforms": [
    "ios"
  ]
}
--- End of Cordova JSON Snippet ---
```

**Comment by AraHovakimyan** [comment]
Hi jfoclpf

The problem you mentioned is not related to this plugin as the file 'CDVWKWebViewEngine.h' is not referenced from this plugin.
Probably your problem is related to the fact that your project uses plugin
"cordova-plugin-wkwebviewxhrfix"
instead of
"AraHovakimyan/cordova-plugin-wkwebviewxhrfix"
If you want your project to work correctly for Cordova-ios version 6.1.1
You need

First remove the cordova-plugin-wkwebviewxhrfix plugin by
cordova plugin rm cordova-plugin-wkwebviewxhrfix

Install plugin AraHovakimyan/cordova-plugin-wkwebviewxhrfix by
cordova plugin add https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix

Note: If you have used the plugin "cordova-plugin-wkwebview-engine" before, you must also uninstall it as this plugin is unnecessary for Cordova-ios version 6.1.1
cordova plugin rm cordova-plugin-wkwebview-engine

Hope the above-mentioned steps will fix the issue.

**Comment by jfoclpf** [comment]
Hi @AraHovakimyan in the meantime I installed another plugin that does the same, but I had initially already run

`cordova plugin add https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix`

**Comment by AraHovakimyan** [comment]
I'm glad that you managed to solve your problem. Just want to say that It is often necessary to understand the cause of the problem and not rush to write a negative comment.

**Comment by jfoclpf** [comment]
I understand your frustration, you developed a free and open plugin and people just protest without further investigation. 

But put yourself in my position. My app has dozens of plugins, and the app builds successfully. I install this plugin according to instruction and the build fails. I remove it and builds successfully again. 

I have no time to further investigation why it fails. I know it may seem unfair, I am also a developer of open source and free apps, but I deal with dozens of issues and I try to stick with what is relevant. Hope you understand

**Comment by AraHovakimyan** [comment]
I just wanted to say that the problem you were having had nothing to do with this plugin.

**Comment by HarelM** [comment]
Hi,
First and foremost that for this awesome plugin!
I also has the same issue, I believe that is described in this thread (to some extent).
i.e.
I added the plugin using:
`cordova plugin add @ahovakimyan/cordova-plugin-wkwebviewxhrfix` which built locally just fine.
But when this ran in CI (which operates on a clean machine with no preinstalled plugins etc) the build falied.
See this build log:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/43918928/job/4cvw2pvne1xxf5gj
The following is the build error:
```
In file included from /Users/appveyor/projects/site/IsraelHiking.Web/platforms/ios/Israel Hiking Map/Plugins/cordova-plugin-wkwebviewxhrfix/CDVWKWebViewEngine+FileXhrFix.m:9:
/Users/appveyor/projects/site/IsraelHiking.Web/platforms/ios/Israel Hiking Map/Plugins/cordova-plugin-wkwebviewxhrfix/CDVWKWebViewEngine+FileXhrFix.h:9:9: fatal error: 'CDVWKWebViewEngine.h' file not found
#import "CDVWKWebViewEngine.h"
        ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

@AraHovakimyan you are correct that this plugin doesn't reference this file.

I also maintain a fork of a plugin that was no longer maintained and what I learned is that if the plugin has the same name as another plugin, cordova installation process might get confused and install the other plugin (I think).

What I did in my plugin in order to resolve this is made sure the plugin name and the npm package that it is published with are identical.

I'll see if I can open an issue for cordova team to fix this, but until then I think that changing this plugin name to match the npm package might be a good solution (and also it's cleaner from my point of view).

As a workaround, the suggestion here to use the git repo URL instead of installing the npm package will work (and I think also adds some confidence that what I say might be the issue as when you install the git repo URL you basically install the "old" plugin but use a different code base and not install a "different" plugin).

Thanks again for all the work invested in this, and I hope this wasn't too long :-)

**Comment by HarelM** [comment]
Thanks for returning to me so quickly!
The above didn't solve my problem.
I never installed the "previous" plugin but cordova CLI installs it by mistake in my CI because the id in the plugin.xml file in this repo was not changed to match the npm package name, so cordova gets confused.
I've created a fork here:
https://github.com/IsraelHikingMap/cordova-plugin-wkwebviewxhrfix
With some fixes, the main change is the name in the package.json file to "revert" to match the id in the plugin.xml.

**Comment by AraHovakimyan** [comment]
:):):) I understood what do you mean

Is your fork fix your issue ?
cordova plugin add https://github.com/IsraelHikingMap/cordova-plugin-wkwebviewxhrfix

I will think about how can I fix this issue.

**Comment by AraHovakimyan** [comment]
Try to use GitHub version 
`cordova plugin add https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix`

**Comment by HarelM** [comment]
I did try the git url of this repo, it didn't work as well :-)
My fork solved my issue.
I think that changing the id in this repo to @AraHovakimyan/cordova... should fix this issue.

**Comment by AraHovakimyan** [comment]
I think it is not possible to use the symbol **"/"** in the name of ID like this "AAAA/BBBB" :).

Thank you

**Comment by HarelM** [comment]
You might be right... Bummer...

**Comment by AraHovakimyan** [comment]
Hi HarelM,

 I have updated the plugin id based on your suggestion(v1.0.1).
If you have time, you can check if it works for you.

Thank you very much

**Comment by HarelM** [comment]
Thanks for the info, I hope to be able to test it in the next few days.

**Comment by AraHovakimyan** [comment]
Thank you again.

**Comment by HarelM** [comment]
version 1.0.1 is not in npm yet... Are you planning on publishing it?

**Comment by AraHovakimyan** [comment]
Yes I plan to publish this version on npm

**Comment by HarelM** [comment]
Build seems to pass now with latest code from github. Haven't checked that it is working, but I support it does since there were no real code changes.

**Comment by AraHovakimyan** [comment]
Thank you so much

**Comment by AraHovakimyan** [comment]
Hi HarelM,
Today I published the fix on NPM.
Thank you for all.

**Comment by eugenmamaev** [comment]
Hi, @AraHovakimyan. Looks like the last fix did not work. I spent a lot of time to find the reason. I already used your module in our project and all was good. I removed all slashes in names and Ids and it installed successfully. My thoughts, the best Idea is to use a suffix in the name of the plugin.
Anyway, I appreciated you for this plugin )

**Comment by AraHovakimyan** [comment]
Hi @eugenmamaev,

I can't reproduce. Can you provide details about the errors? 
 And which version of Cordova and Node do you use?

Thank you.
