### ISSUE TITLE
'CDVWKWebViewEngine.h' file not found

### ISSUE THREAD

**Issue by dshark95** [AraHovakimyan/cordova-plugin-wkwebviewxhrfix#9]
<img width="703" alt="Screenshot 2023-03-07 at 11 30 17 AM" src="https://user-images.githubusercontent.com/60464500/223313463-a409a80a-52ad-4df6-b388-25dc950c8f8d.png">

Hi, I notice that after I had type in the command `cordova plugin add @ahovakimyan/cordova-plugin-wkwebviewxhrfix` , it auto install `cordova-plugin-wkwebviewxhrfix` after the `@ahovakimyan/cordova-plugin-wkwebviewxhrfix` plugin is install, I had already delete package.lock.json, and remove platforms and plugins folder, it still give me the same behaviour.

**Comment by AraHovakimyan** [comment]
Such a file doesn't exist in this plugin.
This file is from another plugin.
Try to 
1. First remove the cordova-plugin-wkwebviewxhrfix plugin by
`cordova plugin rm cordova-plugin-wkwebviewxhrfix`

2.Install plugin AraHovakimyan/cordova-plugin-wkwebviewxhrfix by
`cordova plugin add https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix`

**Comment by AraHovakimyan** [comment]
OR try to use this fork 
`cordova plugin add https://github.com/IsraelHikingMap/cordova-plugin-wkwebviewxhrfix`

Please let me know if this approach will help you to fix your issue.

Based on discussion
https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix/issues/5#issuecomment-1162193487

**Comment by dshark95** [comment]
Hi @AraHovakimyan , thanks for the suggestion , for now already working fine with your solution.
